language: php
php:
  - 5.5
  - 5.4
  - 5.3
  - hhvm 

before_script:
  - "pushd /tmp && git clone https://github.com/php/pecl-php-runkit.git && pushd runkit && pecl install package.xml && popd && popd"
  - composer install
